# -*- coding: utf-8 -*-
"""streamlit app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NM3nuNbdxwMU0koIm2EBDgGBr7UJiCcb
"""
# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# import matplotlib.patches as mpatches
# 
# st.set_page_config(
#     page_title="SPK Pemilihan Pelatihan Teknik Industri",
#     page_icon="🎓",
#     layout="wide"
# )
# 
# st.title("🎓 Sistem Pendukung Keputusan")
# st.subheader("Pemilihan Program Pelatihan Keterampilan Mahasiswa Teknik Industri")
# st.caption("Menggunakan Metode Fuzzy Logic | Universitas Telkom Purwokerto | 2026")
# st.divider()
# 
# 
# # ─────────────────────────────────────────────
# # FUNGSI KEANGGOTAAN
# # ─────────────────────────────────────────────
# 
# def trimf(x, a, b, c):
#     if x <= a or x >= c:
#         return 0.0
#     elif a < x <= b:
#         return (x - a) / (b - a)
#     else:
#         return (c - x) / (c - b)
# 
# def trapmf_left(x, a, b):
#     if x <= a:
#         return 1.0
#     elif x >= b:
#         return 0.0
#     else:
#         return (b - x) / (b - a)
# 
# def trapmf_right(x, a, b):
#     if x <= a:
#         return 0.0
#     elif x >= b:
#         return 1.0
#     else:
#         return (x - a) / (b - a)
# 
# def fuzzy_biaya(x):
#     rendah = trapmf_left(x, 2_000_000, 4_000_000)
#     sedang = trimf(x, 2_000_000, 4_000_000, 6_500_000)
#     tinggi = trapmf_right(x, 4_000_000, 6_500_000)
#     return {"Rendah": rendah, "Sedang": sedang, "Tinggi": tinggi}
# 
# def fuzzy_lowongan_pekerjaan(x):
#     rendah = trapmf_left(x, 857, 1_100)
#     sedang = trimf(x, 857, 1_100, 1_409)
#     tinggi = trapmf_right(x, 1_100, 1_409)
#     return {"Rendah": rendah, "Sedang": sedang, "Tinggi": tinggi}
# 
# RULES = [
#     ("Rendah", "Tinggi",  "Tinggi"),
#     ("Rendah", "Sedang",  "Tinggi"),
#     ("Rendah", "Rendah",  "Sedang"),
#     ("Sedang", "Tinggi",  "Sedang"),
#     ("Sedang", "Sedang",  "Sedang"),
#     ("Sedang", "Rendah",  "Rendah"),
#     ("Tinggi", "Tinggi",  "Sedang"),
#     ("Tinggi", "Sedang",  "Rendah"),
#     ("Tinggi", "Rendah",  "Rendah"),
# ]
# 
# OUTPUT_CENTERS = {"Rendah": 20, "Sedang": 50, "Tinggi": 80}
# 
# def inferensi(biaya_val, lowongan_val):
#     mb = fuzzy_biaya(biaya_val)
#     ml = fuzzy_lowongan_pekerjaan(lowongan_val)
# 
#     fired = []
#     num, den = 0.0, 0.0
#     for rb, rl, out in RULES:
#         strength = min(mb[rb], ml[rl])
#         fired.append({
#             "IF Biaya": rb,
#             "AND Lowongan Pekerjaan": rl,
#             "THEN Prioritas": out,
#             "mu Biaya": round(mb[rb], 4),
#             "mu Lowongan Pekerjaan": round(ml[rl], 4),
#             "Kekuatan a=min(muB,muL)": round(strength, 4),
#             "Centroid z": OUTPUT_CENTERS[out],
#             "a x z": round(strength * OUTPUT_CENTERS[out], 4),
#         })
#         num += strength * OUTPUT_CENTERS[out]
#         den += strength
# 
#     skor = round(num / den, 2) if den > 0 else 0.0
#     if skor >= 60:
#         kategori = "🟢 Tinggi"
#     elif skor >= 35:
#         kategori = "🟡 Sedang"
#     else:
#         kategori = "🔴 Rendah"
# 
#     return mb, ml, fired, skor, kategori, num, den
# 
# 
# # ─────────────────────────────────────────────
# # GRAFIK
# # ─────────────────────────────────────────────
# 
# def plot_biaya(nilai=None):
#     x = np.linspace(0, 7_500_000, 500)
#     r = [trapmf_left(v, 2_000_000, 4_000_000) for v in x]
#     s = [trimf(v, 2_000_000, 4_000_000, 6_500_000) for v in x]
#     t = [trapmf_right(v, 4_000_000, 6_500_000) for v in x]
# 
#     fig, ax = plt.subplots(figsize=(6, 3))
#     ax.plot(x / 1e6, r, 'b-',  label='Rendah')
#     ax.plot(x / 1e6, s, 'g--', label='Sedang')
#     ax.plot(x / 1e6, t, 'r:',  label='Tinggi')
#     if nilai:
#         ax.axvline(x=nilai / 1e6, color='k', linestyle='--',
#                    linewidth=1.5, label=f'Input: Rp{nilai:,.0f}')
#     ax.set_xlabel("Biaya (juta Rp)")
#     ax.set_ylabel("Derajat Keanggotaan (mu)")
#     ax.set_title("Fungsi Keanggotaan: Biaya")
#     ax.legend(fontsize=8)
#     ax.set_ylim(-0.05, 1.1)
#     ax.grid(alpha=0.3)
#     return fig
# 
# def plot_lowongan_pekerjaan(nilai=None):
#     x = np.linspace(700, 1600, 500)
#     r = [trapmf_left(v, 857, 1_100) for v in x]
#     s = [trimf(v, 857, 1_100, 1_409) for v in x]
#     t = [trapmf_right(v, 1_100, 1_409) for v in x]
# 
#     fig, ax = plt.subplots(figsize=(6, 3))
#     ax.plot(x, r, 'b-',  label='Rendah')
#     ax.plot(x, s, 'g--', label='Sedang')
#     ax.plot(x, t, 'r:',  label='Tinggi')
#     if nilai:
#         ax.axvline(x=nilai, color='k', linestyle='--',
#                    linewidth=1.5, label=f'Input: {nilai} lowongan pekerjaan')
#     ax.set_xlabel("Jumlah Lowongan Pekerjaan")
#     ax.set_ylabel("Derajat Keanggotaan (mu)")
#     ax.set_title("Fungsi Keanggotaan: Lowongan Pekerjaan")
#     ax.legend(fontsize=8)
#     ax.set_ylim(-0.05, 1.1)
#     ax.grid(alpha=0.3)
#     return fig
# 
# 
# # ─────────────────────────────────────────────
# # SIDEBAR INPUT
# # ─────────────────────────────────────────────
# 
# st.sidebar.header("⚙️ Input Data Pelatihan")
# st.sidebar.caption("Masukkan data biaya dan jumlah lowongan pekerjaan untuk setiap alternatif.")
# st.sidebar.divider()
# 
# pelatihan_list             = ["SAP", "Lean Six Sigma", "AutoCAD"]
# default_biaya              = [4_000_000, 6_500_000, 1_200_000]
# default_lowongan_pekerjaan = [956, 857, 1409]
# inputs = {}
# 
# for i, nama in enumerate(pelatihan_list):
#     st.sidebar.subheader(f"📌 {nama}")
#     b = st.sidebar.number_input(
#         f"Biaya {nama} (Rp)",
#         min_value=0, max_value=20_000_000,
#         value=default_biaya[i], step=100_000,
#         key=f"biaya_{nama}"
#     )
#     l = st.sidebar.number_input(
#         f"Lowongan Pekerjaan {nama}",
#         min_value=0, max_value=10_000,
#         value=default_lowongan_pekerjaan[i], step=10,
#         key=f"low_{nama}"
#     )
#     inputs[nama] = {"biaya": b, "lowongan_pekerjaan": l}
#     st.sidebar.divider()
# 
# st.sidebar.button("🔍 Hitung Prioritas", use_container_width=True, type="primary")
# 
# tab1, tab2, tab3, tab4, tab5 = st.tabs([
#     "📋 Data Input",
#     "📐 Fuzzifikasi",
#     "⚙️ Inferensi",
#     "🧮 Detail Defuzzifikasi",
#     "🏆 Hasil & Ranking",
# ])
# 
# 
# # ─────────────────────────────────────────────
# # TAB 1: DATA INPUT
# # ─────────────────────────────────────────────
# 
# with tab1:
#     st.header("📋 Data Input Pelatihan")
#     st.write(
#         "Berikut adalah data yang digunakan sebagai input sistem. "
#         "Data bersumber dari hasil wawancara dosen Teknik Industri dan riset pada platform JobStreet."
#     )
# 
#     df_input = pd.DataFrame({
#         "Alternatif Pelatihan": pelatihan_list,
#         "Biaya (Rp)": [f"Rp {inputs[n]['biaya']:,}" for n in pelatihan_list],
#         "Jumlah Lowongan Pekerjaan": [inputs[n]['lowongan_pekerjaan'] for n in pelatihan_list],
#     })
#     st.dataframe(df_input, use_container_width=True, hide_index=True)
# 
#     st.divider()
#     st.subheader("📊 Visualisasi Fungsi Keanggotaan")
#     col1, col2 = st.columns(2)
#     with col1:
#         st.pyplot(plot_biaya())
#     with col2:
#         st.pyplot(plot_lowongan_pekerjaan())
# 
#     st.divider()
#     st.subheader("ℹ️ Keterangan Fungsi Keanggotaan")
#     col_a, col_b = st.columns(2)
#     with col_a:
#         st.markdown("""
# **Variabel Biaya:**
# | Himpunan | Jenis Fungsi | Parameter |
# |----------|-------------|-----------|
# | Rendah | Trapesium Kiri | plateau s.d. Rp2.000.000, turun ke Rp4.000.000 |
# | Sedang | Segitiga | naik dari Rp2jt, puncak Rp4jt, turun ke Rp6,5jt |
# | Tinggi | Trapesium Kanan | naik dari Rp4.000.000 ke Rp6.500.000+ |
# """)
#     with col_b:
#         st.markdown("""
# **Variabel Lowongan Pekerjaan:**
# | Himpunan | Jenis Fungsi | Parameter |
# |----------|-------------|-----------|
# | Rendah | Trapesium Kiri | plateau s.d. 857, turun ke 1.100 |
# | Sedang | Segitiga | naik dari 857, puncak 1.100, turun ke 1.409 |
# | Tinggi | Trapesium Kanan | naik dari 1.100 ke 1.409+ |
# """)
# 
# 
# # ─────────────────────────────────────────────
# # TAB 2: FUZZIFIKASI
# # ─────────────────────────────────────────────
# 
# with tab2:
#     st.header("📐 Fuzzifikasi")
#     st.write(
#         "Tahap fuzzifikasi mengubah nilai input crisp (biaya dan lowongan pekerjaan) "
#         "menjadi derajat keanggotaan (mu) pada setiap himpunan linguistik."
#     )
# 
#     for nama in pelatihan_list:
#         b = inputs[nama]["biaya"]
#         l = inputs[nama]["lowongan_pekerjaan"]
#         mb = fuzzy_biaya(b)
#         ml = fuzzy_lowongan_pekerjaan(l)
# 
#         st.subheader(f"📌 {nama}")
#         col1, col2 = st.columns(2)
# 
#         with col1:
#             st.write(f"**Biaya: Rp {b:,}**")
#             df_b = pd.DataFrame({
#                 "Himpunan": list(mb.keys()),
#                 "Derajat Keanggotaan (mu)": [round(v, 4) for v in mb.values()],
#                 "Status": ["Aktif ✅" if round(v, 4) > 0 else "Tidak Aktif ⬜" for v in mb.values()]
#             })
#             st.dataframe(df_b, use_container_width=True, hide_index=True)
#             st.pyplot(plot_biaya(b))
# 
#         with col2:
#             st.write(f"**Lowongan Pekerjaan: {l}**")
#             df_l = pd.DataFrame({
#                 "Himpunan": list(ml.keys()),
#                 "Derajat Keanggotaan (mu)": [round(v, 4) for v in ml.values()],
#                 "Status": ["Aktif ✅" if round(v, 4) > 0 else "Tidak Aktif ⬜" for v in ml.values()]
#             })
#             st.dataframe(df_l, use_container_width=True, hide_index=True)
#             st.pyplot(plot_lowongan_pekerjaan(l))
# 
#         st.divider()
# 
# 
# # ─────────────────────────────────────────────
# # TAB 3: INFERENSI
# # ─────────────────────────────────────────────
# 
# with tab3:
#     st.header("⚙️ Inferensi Fuzzy")
#     st.write(
#         "Tahap inferensi menerapkan 9 aturan fuzzy (rule base) untuk setiap alternatif. "
#         "Kekuatan aturan (alpha) dihitung dengan operator **AND = min(mu Biaya, mu Lowongan Pekerjaan)**."
#     )
# 
#     st.subheader("📋 Rule Base Sistem (9 Aturan)")
#     df_rules = pd.DataFrame(
#         [(i + 1, rb, rl, out) for i, (rb, rl, out) in enumerate(RULES)],
#         columns=["No.", "IF Biaya", "AND Lowongan Pekerjaan", "THEN Prioritas"]
#     )
#     st.dataframe(df_rules, use_container_width=True, hide_index=True)
# 
#     st.divider()
# 
#     for nama in pelatihan_list:
#         b = inputs[nama]["biaya"]
#         l = inputs[nama]["lowongan_pekerjaan"]
#         mb, ml, fired, skor, kat, num, den = inferensi(b, l)
# 
#         st.subheader(f"📌 {nama} — Fired Rules")
#         st.caption(f"Input: Biaya = Rp {b:,} | Lowongan Pekerjaan = {l}")
# 
#         df_fired = pd.DataFrame(fired)[[
#             "IF Biaya", "AND Lowongan Pekerjaan", "THEN Prioritas",
#             "mu Biaya", "mu Lowongan Pekerjaan", "Kekuatan a=min(muB,muL)"
#         ]]
#         df_fired.index = range(1, len(df_fired) + 1)
# 
#         def highlight_fired(row):
#             if row["Kekuatan a=min(muB,muL)"] > 0:
#                 return ["background-color: #d4edda; color: #155724"] * len(row)
#             return ["color: #999999"] * len(row)
# 
#         st.dataframe(
#             df_fired.style.apply(highlight_fired, axis=1),
#             use_container_width=True
#         )
# 
#         aktif = sum(1 for f in fired if f["Kekuatan a=min(muB,muL)"] > 0)
#         st.caption(
#             f"✅ **{aktif} dari 9 rule aktif** (alpha > 0) ditandai hijau. "
#             f"Skor defuzzifikasi: **{skor}** → {kat}"
#         )
#         st.divider()
# 
# 
# # ─────────────────────────────────────────────
# # TAB 4: DETAIL DEFUZZIFIKASI
# # ─────────────────────────────────────────────
# 
# with tab4:
#     st.header("🧮 Detail Defuzzifikasi (Weighted Average / Centroid)")
# 
#     st.info(
#         "**Rumus Defuzzifikasi Weighted Average:**\n\n"
#         "z* = Sigma(alpha_i * z_i) / Sigma(alpha_i)\n\n"
#         "Di mana:\n"
#         "- alpha_i = kekuatan rule ke-i = min(mu_Biaya, mu_LowonganPekerjaan)\n"
#         "- z_i = nilai centroid output (Rendah=20, Sedang=50, Tinggi=80)\n"
#         "- z* = skor akhir prioritas (0–100)"
#     )
# 
#     st.subheader("📌 Nilai Centroid Output")
#     df_centroid = pd.DataFrame({
#         "Himpunan Output": ["Rendah", "Sedang", "Tinggi"],
#         "Rentang": ["0 – 40", "30 – 70", "60 – 100"],
#         "Nilai Centroid (z)": [20, 50, 80],
#         "Keterangan": [
#             "Pelatihan kurang direkomendasikan",
#             "Pelatihan cukup direkomendasikan",
#             "Pelatihan sangat direkomendasikan"
#         ]
#     })
#     st.dataframe(df_centroid, use_container_width=True, hide_index=True)
# 
#     st.divider()
# 
#     for nama in pelatihan_list:
#         b = inputs[nama]["biaya"]
#         l = inputs[nama]["lowongan_pekerjaan"]
#         mb, ml, fired, skor, kat, num, den = inferensi(b, l)
# 
#         st.subheader(f"📌 Perhitungan Lengkap: {nama}")
#         st.caption(f"Input: Biaya = Rp {b:,} | Lowongan Pekerjaan = {l}")
# 
#         df_detail = pd.DataFrame(fired)[[
#             "IF Biaya", "AND Lowongan Pekerjaan", "THEN Prioritas",
#             "Kekuatan a=min(muB,muL)", "Centroid z", "a x z"
#         ]]
#         df_detail.index = range(1, len(df_detail) + 1)
# 
#         total_row = pd.DataFrame([{
#             "IF Biaya": "—",
#             "AND Lowongan Pekerjaan": "—",
#             "THEN Prioritas": "TOTAL",
#             "Kekuatan a=min(muB,muL)": round(den, 4),
#             "Centroid z": "—",
#             "a x z": round(num, 4),
#         }])
#         df_detail_total = pd.concat([df_detail, total_row], ignore_index=True)
# 
#         st.dataframe(df_detail_total, use_container_width=True)
# 
#         col1, col2, col3 = st.columns(3)
#         col1.metric("Sigma (alpha x z)", f"{num:.4f}")
#         col2.metric("Sigma alpha", f"{den:.4f}")
#         col3.metric("z* = Sigma(a*z) / Sigma(a)", f"{skor}")
# 
#         st.markdown(f"**Perhitungan:** z* = {num:.4f} / {den:.4f} = **{skor}** → {kat}")
#         st.divider()
# 
# 
# # ─────────────────────────────────────────────
# # TAB 5: HASIL & RANKING
# # ─────────────────────────────────────────────
# 
# with tab5:
#     st.header("🏆 Hasil Defuzzifikasi & Ranking")
#     st.write(
#         "Skor akhir dihitung menggunakan metode **Weighted Average (Centroid)**. "
#         "Semakin tinggi skor, semakin direkomendasikan pelatihan tersebut."
#     )
# 
#     hasil = []
#     for nama in pelatihan_list:
#         b = inputs[nama]["biaya"]
#         l = inputs[nama]["lowongan_pekerjaan"]
#         _, _, _, skor, kat, _, _ = inferensi(b, l)
#         hasil.append({
#             "Pelatihan": nama,
#             "Biaya (Rp)": b,
#             "Lowongan Pekerjaan": l,
#             "Skor Fuzzy": skor,
#             "Kategori": kat
#         })
# 
#     hasil_df = (
#         pd.DataFrame(hasil)
#         .sort_values("Skor Fuzzy", ascending=False)
#         .reset_index(drop=True)
#     )
#     hasil_df.index += 1
#     hasil_df["Ranking"] = hasil_df.index
#     hasil_df_display = hasil_df.copy()
#     hasil_df_display["Biaya (Rp)"] = hasil_df_display["Biaya (Rp)"].apply(lambda x: f"Rp {x:,}")
# 
#     st.dataframe(
#         hasil_df_display[["Ranking", "Pelatihan", "Biaya (Rp)", "Lowongan Pekerjaan", "Skor Fuzzy", "Kategori"]],
#         use_container_width=True,
#         hide_index=True
#     )
# 
#     st.divider()
#     st.subheader("📊 Grafik Skor Prioritas")
#     fig, ax = plt.subplots(figsize=(7, 4))
#     colors = []
#     for s in hasil_df["Skor Fuzzy"]:
#         if s >= 60:
#             colors.append("#28a745")
#         elif s >= 35:
#             colors.append("#ffc107")
#         else:
#             colors.append("#dc3545")
# 
#     bars = ax.barh(hasil_df["Pelatihan"], hasil_df["Skor Fuzzy"], color=colors, height=0.5)
#     for bar, val in zip(bars, hasil_df["Skor Fuzzy"]):
#         ax.text(
#             bar.get_width() + 0.5,
#             bar.get_y() + bar.get_height() / 2,
#             f"{val}", va='center', fontsize=11, fontweight='bold'
#         )
#     ax.set_xlim(0, 115)
#     ax.set_xlabel("Skor Fuzzy (0–100)")
#     ax.set_title("Ranking Prioritas Pelatihan Teknik Industri")
#     ax.axvline(x=60, color='g', linestyle='--', alpha=0.5, label='Batas Tinggi (>=60)')
#     ax.axvline(x=35, color='orange', linestyle='--', alpha=0.5, label='Batas Sedang (>=35)')
#     patches = [
#         mpatches.Patch(color='#28a745', label='Prioritas Tinggi (>=60)'),
#         mpatches.Patch(color='#ffc107', label='Prioritas Sedang (35-59)'),
#         mpatches.Patch(color='#dc3545', label='Prioritas Rendah (<35)'),
#     ]
#     ax.legend(handles=patches, fontsize=8)
#     ax.grid(axis='x', alpha=0.3)
#     st.pyplot(fig)
# 
#     st.divider()
#     st.subheader("📊 Perbandingan Kriteria Pelatihan")
# 
#     fig2, axes = plt.subplots(1, 2, figsize=(10, 4))
#     bar_colors = ['#4e8cff', '#ff7f50', '#82ca9d']
# 
#     axes[0].bar(hasil_df["Pelatihan"], hasil_df["Biaya (Rp)"] / 1e6, color=bar_colors)
#     axes[0].set_title("Biaya Pelatihan (juta Rp)")
#     axes[0].set_ylabel("Juta Rupiah")
#     axes[0].grid(axis='y', alpha=0.3)
# 
#     axes[1].bar(hasil_df["Pelatihan"], hasil_df["Lowongan Pekerjaan"], color=bar_colors)
#     axes[1].set_title("Jumlah Lowongan Pekerjaan")
#     axes[1].set_ylabel("Jumlah Lowongan")
#     axes[1].grid(axis='y', alpha=0.3)
# 
#     plt.tight_layout()
#     st.pyplot(fig2)
# 
#     st.divider()
#     st.subheader("💡 Kesimpulan Rekomendasi")
#     top = hasil_df.iloc[0]
#     st.success(
#         f"Pelatihan yang paling direkomendasikan adalah: **{top['Pelatihan']}** "
#         f"dengan skor fuzzy **{top['Skor Fuzzy']}** ({top['Kategori']})"
#     )
#     st.info(
#         "Rekomendasi didasarkan pada dua kriteria objektif:\n"
#         "- **Biaya pelatihan** — lebih rendah lebih baik (Rendah → Prioritas Tinggi)\n"
#         "- **Jumlah lowongan pekerjaan** — lebih banyak lebih baik (Tinggi → Prioritas Tinggi)\n\n"
#         "Data bersumber dari platform **JobStreet** dan dapat diperbarui melalui panel input di kiri."
#     )
# 
#     with st.expander("📖 Cara Membaca Hasil"):
#         st.markdown("""
# **Threshold Kategori:**
# - **Tinggi** (skor >= 60): Sangat direkomendasikan — biaya terjangkau dan/atau banyak lowongan.
# - **Sedang** (35 <= skor < 60): Cukup direkomendasikan — ada trade-off biaya vs lowongan.
# - **Rendah** (skor < 35): Kurang direkomendasikan — biaya tinggi dan/atau lowongan terbatas.
# 
# **Metode:** Weighted Average Centroid (Mamdani)
# **Rule Base:** 9 aturan fuzzy (matriks 3x3 Biaya x Lowongan Pekerjaan)
# **Output Centroid:** Rendah=20, Sedang=50, Tinggi=80
#         """)
import urllib.request
print("IP Tunnel:", urllib.request.urlopen('https://ipv4.icanhazip.com').read().decode('utf8').strip('\n'))

!lt --port 8501 --subdomain your-unique-subdomain
